<a href="https://colab.research.google.com/github/PJunior17/pytorch_tutorial/blob/main/Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pytorch Fundamentals**

Here is a link to the documentation, I suggest using this link often
https://pytorch.org/docs/stable/index.html

# Introduction to Tensors

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch


## Creating Tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
# Returns the number of dimensions
scalar.ndim

0

In [9]:
# Get tensor back as a python int
scalar.item()

7

In [10]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [11]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([2])

In [16]:
# Matrix
MATRIX = torch.tensor([[1,2],
                       [2,3]])
MATRIX

tensor([[1, 2],
        [2, 3]])

In [17]:
MATRIX.ndim

2

In [18]:
MATRIX.shape

torch.Size([2, 2])

In [19]:
# TENSOR
TENSOR = torch.tensor([[[1,2],
                        [2,3]]])

In [20]:
TENSOR.ndim

3

In [21]:
TENSOR.shape

torch.Size([1, 2, 2])

### Random Tensors
We are going to start our tensors with random numbers and then the model will adjust the random numbers to better fit the data and give us an output. This is the basis of deep learning.

In [29]:
# Create a random Tensor of size (3,4)
random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.5017, 0.2519, 0.4093, 0.9670],
         [0.0785, 0.7541, 0.0540, 0.9711],
         [0.6481, 0.9105, 0.7943, 0.1361]],

        [[0.9027, 0.8092, 0.5193, 0.2433],
         [0.1021, 0.7197, 0.0623, 0.8182],
         [0.3059, 0.0253, 0.6194, 0.1519]]])

In [30]:
random_tensor.ndim

3

In [31]:
# Create a random tensor with similar shape to an image
random_size_img_tensor = torch.rand(size=(244,244,3)) #height, width, color channel (R=1, G=2, B=3)
random_size_img_tensor.shape, random_size_img_tensor.ndim

(torch.Size([244, 244, 3]), 3)

### Zeros and Ones Tensor

In [32]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
#all tensors will be of type float unless explicitly stated otherwise
ones.dtype

torch.float32

### Creating a range of tensors and tensor-like

In [37]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
#creating tensor-like
#the _like will create a tensor that is like another one you have already made
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

In [41]:
float32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=None, #how much memory your tensor will take, default is 32
                              device=None, #what device your tensor is on
                              requires_grad=False) #whether to track the gradients with tensors operations

In [42]:
float32_tensor.dtype

torch.float32

In [47]:
float16_tensor = torch.tensor([1,2,23],
                              dtype=torch.float16)

In [48]:
float16_tensor.dtype

torch.float16

## Getting information from tensors

3 attributes and how to get them
1. Datatype - tensor.dtype
2. Shape - tensor.shape
3. Device - tensor.device


In [67]:
some_tensor = torch.rand(3,4)
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)

torch.float32
torch.Size([3, 4])
cpu


## Manuipulating Tensors

Operations Include
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

> Matrix Multiplication Rules
1. Inner dimensions need to be equal
    * (3, 2) x (2, 5)
2. Resulting shape will be the outer dimensions
    * shape of the above multiplication will be (3, 5)




In [68]:
tensor = torch.tensor([1,2,3])
print(torch.add(tensor, 10))
tensor + 10

tensor([11, 12, 13])


tensor([11, 12, 13])

In [69]:
print(torch.sub(tensor,10))
tensor - 10

tensor([-9, -8, -7])


tensor([-9, -8, -7])

In [70]:
#These are element-wise
print(torch.mul(tensor, 10))
tensor * 10

tensor([10, 20, 30])


tensor([10, 20, 30])

In [71]:
print(torch.divide(tensor,10))
tensor / 10

tensor([0.1000, 0.2000, 0.3000])


tensor([0.1000, 0.2000, 0.3000])

In [72]:
#matrix multiplication
#try to use this rather than write a for loop
torch.matmul(tensor, tensor)

tensor(14)

In [73]:
#if the matrix is not the right size you need you can switch the axis by transposing it and then multiplying it
a = torch.rand(3,4)
b = torch.rand(3,4)
torch.matmul(a, b.T), a.shape, b.T.shape

(tensor([[0.5738, 0.3551, 0.5997],
         [0.8553, 0.5553, 0.8491],
         [1.0746, 0.7893, 1.2535]]),
 torch.Size([3, 4]),
 torch.Size([4, 3]))

## Tensor Aggregation

In [75]:
x = torch.arange(1,11)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
torch.min(x), torch.max(x)

(tensor(1), tensor(10))

In [88]:
#arange makes it into a long dtype so we must change the type to float or complex to use mean
x = x.type(torch.float32)
torch.mean(x)

tensor(5.5000)

In [89]:
torch.sum(x)

tensor(55.)