<a href="https://colab.research.google.com/github/PJunior17/pytorch_tutorial/blob/main/Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pytorch Fundamentals**

Here is a link to the documentation, I suggest using this link often
https://pytorch.org/docs/stable/index.html

# Introduction to Tensors

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch


## Creating Tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# Returns the number of dimensions
scalar.ndim

0

In [ ]:
# Get tensor back as a python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
MATRIX = torch.tensor([[1,2],
                       [2,3]])
MATRIX

tensor([[1, 2],
        [2, 3]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2],
                        [2,3]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 2, 2])

### Random Tensors
We are going to start our tensors with random numbers and then the model will adjust the random numbers to better fit the data and give us an output. This is the basis of deep learning.

In [ ]:
# Create a random Tensor of size (3,4)
random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.8472, 0.2870, 0.5089, 0.0455],
         [0.6631, 0.8720, 0.3973, 0.5403],
         [0.2034, 0.7375, 0.1352, 0.9503]],

        [[0.1312, 0.6105, 0.1760, 0.4640],
         [0.7001, 0.7557, 0.4895, 0.8713],
         [0.3194, 0.6734, 0.9178, 0.3810]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
# Create a random tensor with similar shape to an image
random_size_img_tensor = torch.rand(size=(244,244,3)) #height, width, color channel (R=1, G=2, B=3)
random_size_img_tensor.shape, random_size_img_tensor.ndim

(torch.Size([244, 244, 3]), 3)

### Zeros and Ones Tensor

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#all tensors will be of type float unless explicitly stated otherwise
ones.dtype

torch.float32

### Creating a range of tensors and tensor-like

In [ ]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#creating tensor-like
#the _like will create a tensor that is like another one you have already made
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

In [ ]:
float32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=None, #how much memory your tensor will take, default is 32
                              device=None, #what device your tensor is on
                              requires_grad=False) #whether to track the gradients with tensors operations

In [ ]:
float32_tensor.dtype

torch.float32

In [ ]:
float16_tensor = torch.tensor([1,2,23],
                              dtype=torch.float16)

In [ ]:
float16_tensor.dtype

torch.float16

## Getting information from tensors

3 attributes and how to get them
1. Datatype - tensor.dtype
2. Shape - tensor.shape
3. Device - tensor.device


In [ ]:
some_tensor = torch.rand(3,4)
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)

torch.float32
torch.Size([3, 4])
cpu


## Manuipulating Tensors

Operations Include
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

> Matrix Multiplication Rules
1. Inner dimensions need to be equal
    * (3, 2) x (2, 5)
2. Resulting shape will be the outer dimensions
    * shape of the above multiplication will be (3, 5)




In [ ]:
tensor = torch.tensor([1,2,3])
print(torch.add(tensor, 10))
tensor + 10

tensor([11, 12, 13])


tensor([11, 12, 13])

In [ ]:
print(torch.sub(tensor,10))
tensor - 10

tensor([-9, -8, -7])


tensor([-9, -8, -7])

In [ ]:
#These are element-wise
print(torch.mul(tensor, 10))
tensor * 10

tensor([10, 20, 30])


tensor([10, 20, 30])

In [ ]:
print(torch.divide(tensor,10))
tensor / 10

tensor([0.1000, 0.2000, 0.3000])


tensor([0.1000, 0.2000, 0.3000])

In [ ]:
#matrix multiplication
#try to use this rather than write a for loop
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
#if the matrix is not the right size you need you can switch the axis by transposing it and then multiplying it
a = torch.rand(3,4)
b = torch.rand(3,4)
torch.matmul(a, b.T), a.shape, b.T.shape

(tensor([[1.4243, 1.4654, 0.7621],
         [1.3860, 1.5008, 0.8473],
         [1.4293, 1.5952, 0.8337]]),
 torch.Size([3, 4]),
 torch.Size([4, 3]))

## Tensor Aggregation

In [ ]:
x = torch.arange(1,11)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
torch.min(x), torch.max(x)

(tensor(1), tensor(10))

In [ ]:
#arange makes it into a long dtype so we must change the type to float or complex to use mean
x = x.type(torch.float32)
torch.mean(x)

tensor(5.5000)

In [ ]:
torch.sum(x)

tensor(55.)

In [ ]:
#this returns the index of the minimum value
x.argmin()

tensor(0)

In [ ]:
#this returns the index of the maximum value
x.argmax()

tensor(9)

## Reshaping, Stacking, Squeezing, Unsqueezing Tensors

* Reshape - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other or side by side (vstack or hstack)
* Squeeze - removes all 1 dimension from a tensor
* Unsqueeze - add a 1 dimension to a tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
y = torch.arange(1., 11.)
y, y.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
#in order to reshape you need to have a compatible size as the original tensor
y_reshaped = y.reshape(2,5)
y_reshaped, y_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [ ]:
z = y.view(1,10)
z.shape

torch.Size([1, 10])

In [ ]:
#changing z will change y because the view of the tensor shares the same memory as the original tensor
z[:, 0] = 5
z, y

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
#stack
y_stacked = torch.stack([y, y, y, y])
y_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [ ]:
#squeeze
#for some reason this is not working for me but i will troubleshoot that later
print(y_stacked.shape)
print(y_stacked.squeeze().shape)


torch.Size([4, 10])
torch.Size([4, 10])


## Indexing Tensors

In [ ]:
tensor = torch.arange(1,10).reshape(1,3,3)
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
tensor[0][0], tensor[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
tensor[0][0][0], tensor[0,0,0]

(tensor(1), tensor(1))

In [ ]:
# you can use ':' to select all of a target dimension
tensor[:,:,1], tensor[:,1,1]

(tensor([[2, 5, 8]]), tensor([5]))

## Setting the random seed for tensors

In [ ]:
# you have to set the seed everytime you want to generate a random tensor, little inconvienent but okai
torch.manual_seed(17)
rand_tensor = torch.rand(3,4)

torch.manual_seed(17)
rand_tensor2 = torch.rand(3,4)

rand_tensor == rand_tensor2

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])