<a href="https://colab.research.google.com/github/PJunior17/pytorch_tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

# **Lists**

In [ ]:
#this is a regular list
list = [[1,2,3,4,5], [6,7,8,9,10]]
list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# **Numpy Arrays**

In [ ]:
np1 = np.random.rand(3,4)
np1

array([[0.10236751, 0.41533213, 0.59705875, 0.63564095],
       [0.65790704, 0.27903821, 0.75462519, 0.75369794],
       [0.73877003, 0.10747152, 0.94329938, 0.19564577]])

In [ ]:
np1.dtype

dtype('float64')

# **Tensor**

In [ ]:
tensor1 = torch.randn(3,4)
tensor1

tensor([[ 0.5392,  2.0434, -0.3721,  2.0746],
        [ 0.2787, -0.0536, -0.8946, -0.7300],
        [ 0.5995, -0.7672,  0.7534,  0.6070]])

In [ ]:
tensor3d = torch.randn(2, 3, 4)
tensor3d

tensor([[[ 0.0240,  0.1645,  0.9870,  0.6774],
         [-1.1565,  1.0111,  0.4243, -1.6969],
         [-0.9726, -0.3382,  1.0104,  0.1193]],

        [[ 0.4908,  0.2722,  0.7693, -0.6791],
         [-1.3504,  0.0976, -0.7810, -0.2535],
         [-1.7644, -0.9031, -0.8516,  1.6227]]])

In [ ]:
## Tensor out of numpy array
new_tensor = torch.tensor(np1)
new_tensor

tensor([[0.1024, 0.4153, 0.5971, 0.6356],
        [0.6579, 0.2790, 0.7546, 0.7537],
        [0.7388, 0.1075, 0.9433, 0.1956]], dtype=torch.float64)

# **Operations**

In [ ]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# Reshape if we don't know the number of items
my_torch2 = torch.arange(10)
my_torch2 = my_torch.reshape(5, -1)
my_torch2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
my_torch3 = torch.arange(10)
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
#these are dynamic
my_torch3[1] = 10000
print(my_torch3)
my_torch4

tensor([    0, 10000,     2,     3,     4,     5,     6,     7,     8,     9])


tensor([[    0, 10000,     2,     3,     4],
        [    5,     6,     7,     8,     9]])

In [ ]:
#you can grab an element but its really a tensor scalar
my_torch3[1]

tensor(10000)

In [ ]:
# you can grab a slice
mytorch5 = my_torch3.reshape(5, 2)
mytorch5[:,1:]

tensor([[10000],
        [    3],
        [    5],
        [    7],
        [    9]])

# **Math**

In [ ]:
a = torch.tensor([1,2,3,4])
b = torch.tensor([5,6,7,8])

In [ ]:
a + b

tensor([ 6,  8, 10, 12])

In [ ]:
torch.add(a,b)

tensor([ 6,  8, 10, 12])

In [ ]:
b - a

tensor([4, 4, 4, 4])

In [ ]:
a - b

tensor([-4, -4, -4, -4])

In [ ]:
torch.subtract(a,b)

tensor([-4, -4, -4, -4])

In [ ]:
a*b

tensor([ 5, 12, 21, 32])

In [ ]:
torch.multiply(a,b)

tensor([ 5, 12, 21, 32])

In [ ]:
a/b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [ ]:
torch.div(a,b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [ ]:
a%b

tensor([1, 2, 3, 4])

In [ ]:
b%a

tensor([0, 0, 1, 0])

In [ ]:
torch.remainder(a,b)

tensor([1, 2, 3, 4])

In [ ]:
a**b

tensor([    1,    64,  2187, 65536])

In [ ]:
torch.pow(a,b)

tensor([    1,    64,  2187, 65536])

In [ ]:
a.add(b)

tensor([ 6,  8, 10, 12])

In [ ]:
a.add_(b)

tensor([ 6,  8, 10, 12])

In [ ]:
a

tensor([ 6,  8, 10, 12])